ini_pose :
  r_arm_wr_r  : 0.0
  l_arm_wr_r : 0.0
  r_arm_wr_y : 0.0
  l_arm_wr_y : 0.0
  r_arm_wr_p : 0.0
  l_arm_wr_p : 0.0
  r_arm_thumb_y : 0.0
  l_arm_thumb_y : 0.0
  r_arm_thumb_p : -180.0
  l_arm_thumb_p : -180.0
  r_arm_index_p : -180.0
  l_arm_index_p : -180.0
  r_arm_middle_p : -180.0
  l_arm_middle_p : -180.0
  r_arm_finger45_p : -180.0
  l_arm_finger45_p : -180.0